// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peer-to-peer.proto

#ifndef PROTOBUF_peer_2dto_2dpeer_2eproto__INCLUDED
#define PROTOBUF_peer_2dto_2dpeer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace p2p {
class Connect;
class ConnectDefaultTypeInternal;
extern ConnectDefaultTypeInternal _Connect_default_instance_;
class Connect_r;
class Connect_rDefaultTypeInternal;
extern Connect_rDefaultTypeInternal _Connect_r_default_instance_;
class GetUserOnline_r;
class GetUserOnline_rDefaultTypeInternal;
extern GetUserOnline_rDefaultTypeInternal _GetUserOnline_r_default_instance_;
class Info;
class InfoDefaultTypeInternal;
extern InfoDefaultTypeInternal _Info_default_instance_;
class Info_r;
class Info_rDefaultTypeInternal;
extern Info_rDefaultTypeInternal _Info_r_default_instance_;
class Packet;
class PacketDefaultTypeInternal;
extern PacketDefaultTypeInternal _Packet_default_instance_;
}  // namespace p2p

namespace p2p {

namespace protobuf_peer_2dto_2dpeer_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_peer_2dto_2dpeer_2eproto

enum API_ID {
  GETUSERONLINE = 1,
  CONNECT = 2,
  INFO = 3,
  OFFLINE = 4,
  HEART = 5
};
bool API_ID_IsValid(int value);
const API_ID API_ID_MIN = GETUSERONLINE;
const API_ID API_ID_MAX = HEART;
const int API_ID_ARRAYSIZE = API_ID_MAX + 1;

const ::google::protobuf::EnumDescriptor* API_ID_descriptor();
inline const ::std::string& API_ID_Name(API_ID value) {
  return ::google::protobuf::internal::NameOfEnum(
    API_ID_descriptor(), value);
}
inline bool API_ID_Parse(
    const ::std::string& name, API_ID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<API_ID>(
    API_ID_descriptor(), name, value);
}
enum StatusType {
  SUCCESS = 1,
  FAILURE = 2,
  READY = 3,
  CLOSE = 4,
  RUNNING = 5
};
bool StatusType_IsValid(int value);
const StatusType StatusType_MIN = SUCCESS;
const StatusType StatusType_MAX = RUNNING;
const int StatusType_ARRAYSIZE = StatusType_MAX + 1;

const ::google::protobuf::EnumDescriptor* StatusType_descriptor();
inline const ::std::string& StatusType_Name(StatusType value) {
  return ::google::protobuf::internal::NameOfEnum(
    StatusType_descriptor(), value);
}
inline bool StatusType_Parse(
    const ::std::string& name, StatusType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<StatusType>(
    StatusType_descriptor(), name, value);
}
// ===================================================================

class Connect : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:p2p.Connect) */ {
 public:
  Connect();
  virtual ~Connect();

  Connect(const Connect& from);

  inline Connect& operator=(const Connect& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Connect& default_instance();

  static inline const Connect* internal_default_instance() {
    return reinterpret_cast<const Connect*>(
               &_Connect_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Connect* other);

  // implements Message ----------------------------------------------

  inline Connect* New() const PROTOBUF_FINAL { return New(NULL); }

  Connect* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Connect& from);
  void MergeFrom(const Connect& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Connect* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string peer = 1;
  bool has_peer() const;
  void clear_peer();
  static const int kPeerFieldNumber = 1;
  const ::std::string& peer() const;
  void set_peer(const ::std::string& value);
  #if LANG_CXX11
  void set_peer(::std::string&& value);
  #endif
  void set_peer(const char* value);
  void set_peer(const char* value, size_t size);
  ::std::string* mutable_peer();
  ::std::string* release_peer();
  void set_allocated_peer(::std::string* peer);

  // @@protoc_insertion_point(class_scope:p2p.Connect)
 private:
  void set_has_peer();
  void clear_has_peer();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr peer_;
  friend struct protobuf_peer_2dto_2dpeer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Connect_r : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:p2p.Connect_r) */ {
 public:
  Connect_r();
  virtual ~Connect_r();

  Connect_r(const Connect_r& from);

  inline Connect_r& operator=(const Connect_r& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Connect_r& default_instance();

  static inline const Connect_r* internal_default_instance() {
    return reinterpret_cast<const Connect_r*>(
               &_Connect_r_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Connect_r* other);

  // implements Message ----------------------------------------------

  inline Connect_r* New() const PROTOBUF_FINAL { return New(NULL); }

  Connect_r* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Connect_r& from);
  void MergeFrom(const Connect_r& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Connect_r* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .p2p.StatusType t = 1 [default = SUCCESS];
  bool has_t() const;
  void clear_t();
  static const int kTFieldNumber = 1;
  ::p2p::StatusType t() const;
  void set_t(::p2p::StatusType value);

  // @@protoc_insertion_point(class_scope:p2p.Connect_r)
 private:
  void set_has_t();
  void clear_has_t();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  int t_;
  friend struct protobuf_peer_2dto_2dpeer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetUserOnline_r : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:p2p.GetUserOnline_r) */ {
 public:
  GetUserOnline_r();
  virtual ~GetUserOnline_r();

  GetUserOnline_r(const GetUserOnline_r& from);

  inline GetUserOnline_r& operator=(const GetUserOnline_r& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetUserOnline_r& default_instance();

  static inline const GetUserOnline_r* internal_default_instance() {
    return reinterpret_cast<const GetUserOnline_r*>(
               &_GetUserOnline_r_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(GetUserOnline_r* other);

  // implements Message ----------------------------------------------

  inline GetUserOnline_r* New() const PROTOBUF_FINAL { return New(NULL); }

  GetUserOnline_r* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetUserOnline_r& from);
  void MergeFrom(const GetUserOnline_r& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetUserOnline_r* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string user_online = 1;
  int user_online_size() const;
  void clear_user_online();
  static const int kUserOnlineFieldNumber = 1;
  const ::std::string& user_online(int index) const;
  ::std::string* mutable_user_online(int index);
  void set_user_online(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_user_online(int index, ::std::string&& value);
  #endif
  void set_user_online(int index, const char* value);
  void set_user_online(int index, const char* value, size_t size);
  ::std::string* add_user_online();
  void add_user_online(const ::std::string& value);
  #if LANG_CXX11
  void add_user_online(::std::string&& value);
  #endif
  void add_user_online(const char* value);
  void add_user_online(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& user_online() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_user_online();

  // @@protoc_insertion_point(class_scope:p2p.GetUserOnline_r)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> user_online_;
  friend struct protobuf_peer_2dto_2dpeer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Info : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:p2p.Info) */ {
 public:
  Info();
  virtual ~Info();

  Info(const Info& from);

  inline Info& operator=(const Info& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Info& default_instance();

  static inline const Info* internal_default_instance() {
    return reinterpret_cast<const Info*>(
               &_Info_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Info* other);

  // implements Message ----------------------------------------------

  inline Info* New() const PROTOBUF_FINAL { return New(NULL); }

  Info* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Info& from);
  void MergeFrom(const Info& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Info* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string peer = 1;
  int peer_size() const;
  void clear_peer();
  static const int kPeerFieldNumber = 1;
  const ::std::string& peer(int index) const;
  ::std::string* mutable_peer(int index);
  void set_peer(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_peer(int index, ::std::string&& value);
  #endif
  void set_peer(int index, const char* value);
  void set_peer(int index, const char* value, size_t size);
  ::std::string* add_peer();
  void add_peer(const ::std::string& value);
  #if LANG_CXX11
  void add_peer(::std::string&& value);
  #endif
  void add_peer(const char* value);
  void add_peer(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& peer() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_peer();

  // @@protoc_insertion_point(class_scope:p2p.Info)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> peer_;
  friend struct protobuf_peer_2dto_2dpeer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Info_r : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:p2p.Info_r) */ {
 public:
  Info_r();
  virtual ~Info_r();

  Info_r(const Info_r& from);

  inline Info_r& operator=(const Info_r& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Info_r& default_instance();

  static inline const Info_r* internal_default_instance() {
    return reinterpret_cast<const Info_r*>(
               &_Info_r_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(Info_r* other);

  // implements Message ----------------------------------------------

  inline Info_r* New() const PROTOBUF_FINAL { return New(NULL); }

  Info_r* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Info_r& from);
  void MergeFrom(const Info_r& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Info_r* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .p2p.StatusType t = 1 [default = SUCCESS];
  bool has_t() const;
  void clear_t();
  static const int kTFieldNumber = 1;
  ::p2p::StatusType t() const;
  void set_t(::p2p::StatusType value);

  // @@protoc_insertion_point(class_scope:p2p.Info_r)
 private:
  void set_has_t();
  void clear_has_t();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  int t_;
  friend struct protobuf_peer_2dto_2dpeer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Packet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:p2p.Packet) */ {
 public:
  Packet();
  virtual ~Packet();

  Packet(const Packet& from);

  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Packet& default_instance();

  static inline const Packet* internal_default_instance() {
    return reinterpret_cast<const Packet*>(
               &_Packet_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(Packet* other);

  // implements Message ----------------------------------------------

  inline Packet* New() const PROTOBUF_FINAL { return New(NULL); }

  Packet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Packet& from);
  void MergeFrom(const Packet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Packet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string version = 1 [default = "0.1.0"];
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  const ::std::string& version() const;
  void set_version(const ::std::string& value);
  #if LANG_CXX11
  void set_version(::std::string&& value);
  #endif
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  ::std::string* mutable_version();
  ::std::string* release_version();
  void set_allocated_version(::std::string* version);

  // required string user_id = 3;
  bool has_user_id() const;
  void clear_user_id();
  static const int kUserIdFieldNumber = 3;
  const ::std::string& user_id() const;
  void set_user_id(const ::std::string& value);
  #if LANG_CXX11
  void set_user_id(::std::string&& value);
  #endif
  void set_user_id(const char* value);
  void set_user_id(const char* value, size_t size);
  ::std::string* mutable_user_id();
  ::std::string* release_user_id();
  void set_allocated_user_id(::std::string* user_id);

  // optional .p2p.Connect cnt = 4;
  bool has_cnt() const;
  void clear_cnt();
  static const int kCntFieldNumber = 4;
  const ::p2p::Connect& cnt() const;
  ::p2p::Connect* mutable_cnt();
  ::p2p::Connect* release_cnt();
  void set_allocated_cnt(::p2p::Connect* cnt);

  // optional .p2p.Info inf = 5;
  bool has_inf() const;
  void clear_inf();
  static const int kInfFieldNumber = 5;
  const ::p2p::Info& inf() const;
  ::p2p::Info* mutable_inf();
  ::p2p::Info* release_inf();
  void set_allocated_inf(::p2p::Info* inf);

  // required .p2p.API_ID api_id = 2;
  bool has_api_id() const;
  void clear_api_id();
  static const int kApiIdFieldNumber = 2;
  ::p2p::API_ID api_id() const;
  void set_api_id(::p2p::API_ID value);

  // @@protoc_insertion_point(class_scope:p2p.Packet)
 private:
  void set_has_version();
  void clear_has_version();
  void set_has_api_id();
  void clear_has_api_id();
  void set_has_user_id();
  void clear_has_user_id();
  void set_has_cnt();
  void clear_has_cnt();
  void set_has_inf();
  void clear_has_inf();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  static ::google::protobuf::internal::ExplicitlyConstructed< ::std::string> _default_version_;
  ::google::protobuf::internal::ArenaStringPtr version_;
  ::google::protobuf::internal::ArenaStringPtr user_id_;
  ::p2p::Connect* cnt_;
  ::p2p::Info* inf_;
  int api_id_;
  friend struct protobuf_peer_2dto_2dpeer_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Connect

// required string peer = 1;
inline bool Connect::has_peer() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Connect::set_has_peer() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Connect::clear_has_peer() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Connect::clear_peer() {
  peer_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_peer();
}
inline const ::std::string& Connect::peer() const {
  // @@protoc_insertion_point(field_get:p2p.Connect.peer)
  return peer_.GetNoArena();
}
inline void Connect::set_peer(const ::std::string& value) {
  set_has_peer();
  peer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:p2p.Connect.peer)
}
#if LANG_CXX11
inline void Connect::set_peer(::std::string&& value) {
  set_has_peer();
  peer_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:p2p.Connect.peer)
}
#endif
inline void Connect::set_peer(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_peer();
  peer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:p2p.Connect.peer)
}
inline void Connect::set_peer(const char* value, size_t size) {
  set_has_peer();
  peer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:p2p.Connect.peer)
}
inline ::std::string* Connect::mutable_peer() {
  set_has_peer();
  // @@protoc_insertion_point(field_mutable:p2p.Connect.peer)
  return peer_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Connect::release_peer() {
  // @@protoc_insertion_point(field_release:p2p.Connect.peer)
  clear_has_peer();
  return peer_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Connect::set_allocated_peer(::std::string* peer) {
  if (peer != NULL) {
    set_has_peer();
  } else {
    clear_has_peer();
  }
  peer_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), peer);
  // @@protoc_insertion_point(field_set_allocated:p2p.Connect.peer)
}

// -------------------------------------------------------------------

// Connect_r

// required .p2p.StatusType t = 1 [default = SUCCESS];
inline bool Connect_r::has_t() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Connect_r::set_has_t() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Connect_r::clear_has_t() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Connect_r::clear_t() {
  t_ = 1;
  clear_has_t();
}
inline ::p2p::StatusType Connect_r::t() const {
  // @@protoc_insertion_point(field_get:p2p.Connect_r.t)
  return static_cast< ::p2p::StatusType >(t_);
}
inline void Connect_r::set_t(::p2p::StatusType value) {
  assert(::p2p::StatusType_IsValid(value));
  set_has_t();
  t_ = value;
  // @@protoc_insertion_point(field_set:p2p.Connect_r.t)
}

// -------------------------------------------------------------------

// GetUserOnline_r

// repeated string user_online = 1;
inline int GetUserOnline_r::user_online_size() const {
  return user_online_.size();
}
inline void GetUserOnline_r::clear_user_online() {
  user_online_.Clear();
}
inline const ::std::string& GetUserOnline_r::user_online(int index) const {
  // @@protoc_insertion_point(field_get:p2p.GetUserOnline_r.user_online)
  return user_online_.Get(index);
}
inline ::std::string* GetUserOnline_r::mutable_user_online(int index) {
  // @@protoc_insertion_point(field_mutable:p2p.GetUserOnline_r.user_online)
  return user_online_.Mutable(index);
}
inline void GetUserOnline_r::set_user_online(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:p2p.GetUserOnline_r.user_online)
  user_online_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void GetUserOnline_r::set_user_online(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:p2p.GetUserOnline_r.user_online)
  user_online_.Mutable(index)->assign(std::move(value));
}
#endif
inline void GetUserOnline_r::set_user_online(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  user_online_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:p2p.GetUserOnline_r.user_online)
}
inline void GetUserOnline_r::set_user_online(int index, const char* value, size_t size) {
  user_online_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:p2p.GetUserOnline_r.user_online)
}
inline ::std::string* GetUserOnline_r::add_user_online() {
  // @@protoc_insertion_point(field_add_mutable:p2p.GetUserOnline_r.user_online)
  return user_online_.Add();
}
inline void GetUserOnline_r::add_user_online(const ::std::string& value) {
  user_online_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:p2p.GetUserOnline_r.user_online)
}
#if LANG_CXX11
inline void GetUserOnline_r::add_user_online(::std::string&& value) {
  user_online_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:p2p.GetUserOnline_r.user_online)
}
#endif
inline void GetUserOnline_r::add_user_online(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  user_online_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:p2p.GetUserOnline_r.user_online)
}
inline void GetUserOnline_r::add_user_online(const char* value, size_t size) {
  user_online_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:p2p.GetUserOnline_r.user_online)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
GetUserOnline_r::user_online() const {
  // @@protoc_insertion_point(field_list:p2p.GetUserOnline_r.user_online)
  return user_online_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
GetUserOnline_r::mutable_user_online() {
  // @@protoc_insertion_point(field_mutable_list:p2p.GetUserOnline_r.user_online)
  return &user_online_;
}

// -------------------------------------------------------------------

// Info

// repeated string peer = 1;
inline int Info::peer_size() const {
  return peer_.size();
}
inline void Info::clear_peer() {
  peer_.Clear();
}
inline const ::std::string& Info::peer(int index) const {
  // @@protoc_insertion_point(field_get:p2p.Info.peer)
  return peer_.Get(index);
}
inline ::std::string* Info::mutable_peer(int index) {
  // @@protoc_insertion_point(field_mutable:p2p.Info.peer)
  return peer_.Mutable(index);
}
inline void Info::set_peer(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:p2p.Info.peer)
  peer_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void Info::set_peer(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:p2p.Info.peer)
  peer_.Mutable(index)->assign(std::move(value));
}
#endif
inline void Info::set_peer(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  peer_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:p2p.Info.peer)
}
inline void Info::set_peer(int index, const char* value, size_t size) {
  peer_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:p2p.Info.peer)
}
inline ::std::string* Info::add_peer() {
  // @@protoc_insertion_point(field_add_mutable:p2p.Info.peer)
  return peer_.Add();
}
inline void Info::add_peer(const ::std::string& value) {
  peer_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:p2p.Info.peer)
}
#if LANG_CXX11
inline void Info::add_peer(::std::string&& value) {
  peer_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:p2p.Info.peer)
}
#endif
inline void Info::add_peer(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  peer_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:p2p.Info.peer)
}
inline void Info::add_peer(const char* value, size_t size) {
  peer_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:p2p.Info.peer)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Info::peer() const {
  // @@protoc_insertion_point(field_list:p2p.Info.peer)
  return peer_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Info::mutable_peer() {
  // @@protoc_insertion_point(field_mutable_list:p2p.Info.peer)
  return &peer_;
}

// -------------------------------------------------------------------

// Info_r

// required .p2p.StatusType t = 1 [default = SUCCESS];
inline bool Info_r::has_t() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Info_r::set_has_t() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Info_r::clear_has_t() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Info_r::clear_t() {
  t_ = 1;
  clear_has_t();
}
inline ::p2p::StatusType Info_r::t() const {
  // @@protoc_insertion_point(field_get:p2p.Info_r.t)
  return static_cast< ::p2p::StatusType >(t_);
}
inline void Info_r::set_t(::p2p::StatusType value) {
  assert(::p2p::StatusType_IsValid(value));
  set_has_t();
  t_ = value;
  // @@protoc_insertion_point(field_set:p2p.Info_r.t)
}

// -------------------------------------------------------------------

// Packet

// required string version = 1 [default = "0.1.0"];
inline bool Packet::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Packet::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Packet::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Packet::clear_version() {
  version_.ClearToDefaultNoArena(&Packet::_default_version_.get());
  clear_has_version();
}
inline const ::std::string& Packet::version() const {
  // @@protoc_insertion_point(field_get:p2p.Packet.version)
  return version_.GetNoArena();
}
inline void Packet::set_version(const ::std::string& value) {
  set_has_version();
  version_.SetNoArena(&Packet::_default_version_.get(), value);
  // @@protoc_insertion_point(field_set:p2p.Packet.version)
}
#if LANG_CXX11
inline void Packet::set_version(::std::string&& value) {
  set_has_version();
  version_.SetNoArena(
    &Packet::_default_version_.get(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:p2p.Packet.version)
}
#endif
inline void Packet::set_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_version();
  version_.SetNoArena(&Packet::_default_version_.get(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:p2p.Packet.version)
}
inline void Packet::set_version(const char* value, size_t size) {
  set_has_version();
  version_.SetNoArena(&Packet::_default_version_.get(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:p2p.Packet.version)
}
inline ::std::string* Packet::mutable_version() {
  set_has_version();
  // @@protoc_insertion_point(field_mutable:p2p.Packet.version)
  return version_.MutableNoArena(&Packet::_default_version_.get());
}
inline ::std::string* Packet::release_version() {
  // @@protoc_insertion_point(field_release:p2p.Packet.version)
  clear_has_version();
  return version_.ReleaseNoArena(&Packet::_default_version_.get());
}
inline void Packet::set_allocated_version(::std::string* version) {
  if (version != NULL) {
    set_has_version();
  } else {
    clear_has_version();
  }
  version_.SetAllocatedNoArena(&Packet::_default_version_.get(), version);
  // @@protoc_insertion_point(field_set_allocated:p2p.Packet.version)
}

// required .p2p.API_ID api_id = 2;
inline bool Packet::has_api_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Packet::set_has_api_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Packet::clear_has_api_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Packet::clear_api_id() {
  api_id_ = 1;
  clear_has_api_id();
}
inline ::p2p::API_ID Packet::api_id() const {
  // @@protoc_insertion_point(field_get:p2p.Packet.api_id)
  return static_cast< ::p2p::API_ID >(api_id_);
}
inline void Packet::set_api_id(::p2p::API_ID value) {
  assert(::p2p::API_ID_IsValid(value));
  set_has_api_id();
  api_id_ = value;
  // @@protoc_insertion_point(field_set:p2p.Packet.api_id)
}

// required string user_id = 3;
inline bool Packet::has_user_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Packet::set_has_user_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Packet::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Packet::clear_user_id() {
  user_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_user_id();
}
inline const ::std::string& Packet::user_id() const {
  // @@protoc_insertion_point(field_get:p2p.Packet.user_id)
  return user_id_.GetNoArena();
}
inline void Packet::set_user_id(const ::std::string& value) {
  set_has_user_id();
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:p2p.Packet.user_id)
}
#if LANG_CXX11
inline void Packet::set_user_id(::std::string&& value) {
  set_has_user_id();
  user_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:p2p.Packet.user_id)
}
#endif
inline void Packet::set_user_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_user_id();
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:p2p.Packet.user_id)
}
inline void Packet::set_user_id(const char* value, size_t size) {
  set_has_user_id();
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:p2p.Packet.user_id)
}
inline ::std::string* Packet::mutable_user_id() {
  set_has_user_id();
  // @@protoc_insertion_point(field_mutable:p2p.Packet.user_id)
  return user_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Packet::release_user_id() {
  // @@protoc_insertion_point(field_release:p2p.Packet.user_id)
  clear_has_user_id();
  return user_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Packet::set_allocated_user_id(::std::string* user_id) {
  if (user_id != NULL) {
    set_has_user_id();
  } else {
    clear_has_user_id();
  }
  user_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_id);
  // @@protoc_insertion_point(field_set_allocated:p2p.Packet.user_id)
}

// optional .p2p.Connect cnt = 4;
inline bool Packet::has_cnt() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Packet::set_has_cnt() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Packet::clear_has_cnt() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Packet::clear_cnt() {
  if (cnt_ != NULL) cnt_->::p2p::Connect::Clear();
  clear_has_cnt();
}
inline const ::p2p::Connect& Packet::cnt() const {
  // @@protoc_insertion_point(field_get:p2p.Packet.cnt)
  return cnt_ != NULL ? *cnt_
                         : *::p2p::Connect::internal_default_instance();
}
inline ::p2p::Connect* Packet::mutable_cnt() {
  set_has_cnt();
  if (cnt_ == NULL) {
    cnt_ = new ::p2p::Connect;
  }
  // @@protoc_insertion_point(field_mutable:p2p.Packet.cnt)
  return cnt_;
}
inline ::p2p::Connect* Packet::release_cnt() {
  // @@protoc_insertion_point(field_release:p2p.Packet.cnt)
  clear_has_cnt();
  ::p2p::Connect* temp = cnt_;
  cnt_ = NULL;
  return temp;
}
inline void Packet::set_allocated_cnt(::p2p::Connect* cnt) {
  delete cnt_;
  cnt_ = cnt;
  if (cnt) {
    set_has_cnt();
  } else {
    clear_has_cnt();
  }
  // @@protoc_insertion_point(field_set_allocated:p2p.Packet.cnt)
}

// optional .p2p.Info inf = 5;
inline bool Packet::has_inf() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Packet::set_has_inf() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Packet::clear_has_inf() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Packet::clear_inf() {
  if (inf_ != NULL) inf_->::p2p::Info::Clear();
  clear_has_inf();
}
inline const ::p2p::Info& Packet::inf() const {
  // @@protoc_insertion_point(field_get:p2p.Packet.inf)
  return inf_ != NULL ? *inf_
                         : *::p2p::Info::internal_default_instance();
}
inline ::p2p::Info* Packet::mutable_inf() {
  set_has_inf();
  if (inf_ == NULL) {
    inf_ = new ::p2p::Info;
  }
  // @@protoc_insertion_point(field_mutable:p2p.Packet.inf)
  return inf_;
}
inline ::p2p::Info* Packet::release_inf() {
  // @@protoc_insertion_point(field_release:p2p.Packet.inf)
  clear_has_inf();
  ::p2p::Info* temp = inf_;
  inf_ = NULL;
  return temp;
}
inline void Packet::set_allocated_inf(::p2p::Info* inf) {
  delete inf_;
  inf_ = inf;
  if (inf) {
    set_has_inf();
  } else {
    clear_has_inf();
  }
  // @@protoc_insertion_point(field_set_allocated:p2p.Packet.inf)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace p2p

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::p2p::API_ID> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::p2p::API_ID>() {
  return ::p2p::API_ID_descriptor();
}
template <> struct is_proto_enum< ::p2p::StatusType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::p2p::StatusType>() {
  return ::p2p::StatusType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_peer_2dto_2dpeer_2eproto__INCLUDED
